"""
Django settings for Intranet project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more view on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yk$p9j!1rujffj1_^u)663#ycc3t657kodkmj7586dz+-d1i!1'

#  SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


APPEND_SLASH = True


ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'inet.socar-aqs.local', '192.168.0.10']


INTERNAL_IP = ['127.0.0.1']


INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3RD PARTY APPS
    'crispy_forms',
    'ckeditor',
    # 'debug_toolbar',

    # LOCAL APPS
    # 'CommonItems.apps.CommonItemsConfig',
    # 'Transportation.apps.TransportationConfig',
    # 'Warehouse.apps.WarehouseConfig',
    'User.apps.UserConfig',
    # 'HelpDesk.apps.HelpdeskConfig',
    # 'GuestControl.apps.GuestcontrolConfig',
    'News.apps.NewsConfig',
    # 'Directory.apps.DirectoryConfig',
    # 'DocumentLibrary.apps.DocumentlibraryConfig',
    # 'Departments.apps.DepartmentsConfig'


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

ROOT_URLCONF = 'Intranet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.normpath(os.path.join(BASE_DIR, 'Intranet/templates'))],
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Intranet.wsgi.application'


#                                                                                                               Database
#                                                          https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


#                                                                                                    Password validation
#                                           https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#                                                                                                   Internationalization
#                                                                     https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#                                                                                 Static files (CSS, JavaScript, Images)
#                                                              https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

#                                                                                                        CUSTOM SETTINGS
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'welcome'

# --------------------------------------------------------------------------------------------------- 3RD PARTY SETTINGS

#                                                                                                                 CRISPY
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#                                                                                                               CKEDITOR
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_UPLOAD_PATH = "uploads"


#                                                                                                    LDAP AUTHENTICATION
AUTH_LDAP_SERVER_URI = "ldap://192.168.0.1:389"

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=active,ou=django,ou=groups,dc=example,dc=com",
    "is_staff": "cn=staff,ou=django,ou=groups,dc=example,dc=com",
    "is_superuser": "cn=superuser,ou=django,ou=groups,dc=example,dc=com",
}

AUTH_LDAP_FIND_GROUP_PERMS = True

AUTH_LDAP_CACHE_TIMEOUT = 3600

AUTHENTICATION_BACKENDS = (
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
)