"""
Django settings for Intranet project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more view on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yk$p9j!1rujffj1_^u)663#ycc3t657kodkmj7586dz+-d1i!1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# NOT TO ADD SLASH TO THE END OF URL
APPEND_SLASH = False


ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'inet.socar-aqs.local', '192.168.0.10']

INTERNAL_IP = ['127.0.0.1']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3RD PARTY APPS
    'crispy_forms',
    'debug_toolbar',

    # LOCAL APPS
    'CommonItems.apps.CommonitemsConfig',
    'Dashboard.apps.DashboardConfig',
    # 'PeopleOnBoard.apps.PeopleOnBoardConfig',
    # 'Lunchroom.apps.LunchroomConfig',
    'Transportation.apps.TransportationConfig',
    'Warehouse.apps.WarehouseConfig',
    'HumanResources.apps.HumanResourcesConfig',
    'HelpDesk.apps.HelpdeskConfig',
    'GuestControl.apps.GuestcontrolConfig',
    # 'Settings.apps.SettingsConfig',
    'News.apps.NewsConfig',
    'Directory.apps.DirectoryConfig',
    'DocumentLibrary.apps.DocumentlibraryConfig',
    # 'Events.apps.EventsConfig',
    # 'Management.apps.ManagementConfig',
    'Departments.apps.DepartmentsConfig'


]

MIDDLEWARE = [
    # 3RD PARTY MIDDLEWARE
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # END
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

ROOT_URLCONF = 'Intranet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.normpath(os.path.join(BASE_DIR, 'templates'))],
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Intranet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'PeopleOnBoard/static/'),
    os.path.join(BASE_DIR, 'Warehouse/static/'),
    os.path.join(BASE_DIR, 'GuestControl/static/'),
    os.path.join(BASE_DIR, 'HelpDesk/static/'),
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = '/static/'
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# CUSTOM SETTINGS
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard:dashboard_template'
LOGOUT_REDIRECT_URL = 'dashboard:dashboard_template'


# 3RD PARTY SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# DEBUG TOOLBAR SETTINGS
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]


def show_toolbar(request):
    return True


DEBUG_TOOLBAR_CONFIG = {
    'INTERCEPT_REDIRECTS': False,
    'SHOW_TOOLBAR_CALLBACK': show_toolbar
}

AUTH_USER_MODEL = 'HumanResources.CustomUser'
